#!/usr/bin/env python3.11
"""
rr-responder / render_latex.py

Stage 4 of the rr-responder pipeline.

Assemble stage-3 JSONL into a LaTeX-ready markdown document (default) or
a LaTeX appendix block (--format latex).

Markdown output is recommended for human review and iteration. Once happy,
--format latex yields a chunk you can paste into your paper's supplementary
or appendix.

Output structure (Markdown default):
    # Response to Reviewer {R1}
    ## {qid} {first 6 words of title}
    ...
    ## Reviewer {R2}
    ...

CLI:
  python render_latex.py --in PATH.jsonl --out PATH.md|tex
                         [--format md|latex] [--group-by reviewer]

Failure modes:
  - Empty input: writes a placeholder file.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import defaultdict
from typing import Any


def safe_label(text: str, n: int = 6) -> str:
    words = re.findall(r"\w+", text)
    return " ".join(words[:n]) if words else "(untitled)"


def render_md(items: list[dict[str, Any]], group_by_reviewer: bool) -> str:
    lines: list[str] = []
    lines.append("# Draft R&R Response")
    lines.append("")
    lines.append("> 自动生成,需要人工复核。来源:`rr-responder` skill (stage 3+4)。")
    lines.append("")
    lines.append("---")
    lines.append("")

    by_rev: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for it in items:
        by_rev[it.get("reviewer_id", "R?")].append(it)

    if group_by_reviewer:
        ordered_keys = sorted(by_rev.keys(),
                              key=lambda k: (k, int(k.lstrip("R") or 0)))
        for rid in ordered_keys:
            rs = by_rev[rid]
            lines.append(f"# Response to {rid}")
            lines.append("")
            for it in rs:
                qid = it.get("qid", "R?.?")
                atom = it.get("atomic_question", "")
                label = safe_label(atom)
                lines.append(f"## {qid} — {label}")
                lines.append("")
                restated = it.get("restated_question", "")
                if restated:
                    lines.append(f"**Question restated.** {restated}")
                    lines.append("")
                atom2 = it.get("atomic_question", "")
                if atom2 and atom2 != restated:
                    lines.append(f"_Original issue_: {atom2}")
                    lines.append("")
                body = it.get("response_body", "")
                if body:
                    lines.append(body)
                    lines.append("")
                changes = it.get("changes_in_paper", [])
                if changes:
                    lines.append("**Changes in this revision.**")
                    lines.append("")
                    for ch in changes:
                        lines.append(f"- {ch}")
                    lines.append("")
                fu = it.get("followup_qa", [])
                if fu:
                    lines.append("<details><summary>Follow-up Q&A</summary>\n")
                    for qa in fu:
                        lines.append(f"- **Q**: {qa.get('q','')}")
                        lines.append(f"  **A**: {qa.get('a','')}")
                    lines.append("\n</details>\n")
                lines.append("---")
                lines.append("")
    else:
        for it in items:
            qid = it.get("qid", "R?.?")
            atom = it.get("atomic_question", "")
            label = safe_label(atom)
            lines.append(f"## {qid} — {label}")
            lines.append("")
            restated = it.get("restated_question", "")
            if restated:
                lines.append(f"**Question restated.** {restated}")
                lines.append("")
            body = it.get("response_body", "")
            if body:
                lines.append(body)
                lines.append("")
            changes = it.get("changes_in_paper", [])
            if changes:
                lines.append("**Changes in this revision.**")
                lines.append("")
                for ch in changes:
                    lines.append(f"- {ch}")
                lines.append("")
            lines.append("---")
            lines.append("")

    return "\n".join(lines)


def render_latex(items: list[dict[str, Any]], group_by_reviewer: bool) -> str:
    """Emit a LaTeX appendix block you can paste into your response file."""
    def esc(s: str) -> str:
        # minimal LaTeX escaping: backslash, percent, ampersand, dollar
        return (s.replace("\\", r"\textbackslash{}")
                 .replace("&", r"\&")
                 .replace("%", r"\%")
                 .replace("$", r"\$")
                 .replace("#", r"\#"))

    lines: list[str] = []
    lines.append("% Auto-generated by rr-responder. Review and edit before submission.")
    lines.append("% Paste after \\appendix or into your response.tex")
    lines.append("")

    by_rev: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for it in items:
        it["reviewer_id"] = it.get("reviewer_id", "R?")
        by_rev[it["reviewer_id"]].append(it)

    if group_by_reviewer:
        ordered_keys = sorted(by_rev.keys(),
                              key=lambda k: (k, int(k.lstrip("R") or 0)))
        for rid in ordered_keys:
            rs = by_rev[rid]
            lines.append(f"\\section*{{Response to {esc(rid)}}}")
            lines.append("")
            for it in rs:
                qid = it.get("qid", "R?.?")
                atom = it.get("atomic_question", "")
                label = safe_label(atom)
                lines.append(f"\\subsection*{{{esc(qid)} --- {esc(label)}}}")
                lines.append("")
                restated = it.get("restated_question", "")
                if restated:
                    lines.append(f"\\noindent\\textbf{{Question restated.}} {esc(restated)}")
                    lines.append("")
                body = it.get("response_body", "")
                if body:
                    lines.append(esc(body))
                    lines.append("")
                changes = it.get("changes_in_paper", [])
                if changes:
                    lines.append("\\noindent\\textbf{Changes in this revision.}")
                    lines.append("\\begin{itemize}")
                    for ch in changes:
                        lines.append(f"  \\item {esc(ch)}")
                    lines.append("\\end{itemize}")
                    lines.append("")
                fu = it.get("followup_qa", [])
                if fu:
                    lines.append("\\noindent\\textbf{Follow-up Q\\&A.}")
                    lines.append("\\begin{itemize}")
                    for qa in fu:
                        lines.append(f"  \\item \\textbf{{Q:}} {esc(qa.get('q',''))}")
                        lines.append(f"        \\textbf{{A:}} {esc(qa.get('a',''))}")
                    lines.append("\\end{itemize}")
                    lines.append("")
    else:
        for it in items:
            qid = it.get("qid", "R?.?")
            atom = it.get("atomic_question", "")
            label = safe_label(atom)
            lines.append(f"\\subsection*{{{esc(qid)} --- {esc(label)}}}")
            lines.append("")
            restated = it.get("restated_question", "")
            if restated:
                lines.append(f"\\noindent\\textbf{{Question restated.}} {esc(restated)}")
                lines.append("")
            body = it.get("response_body", "")
            if body:
                lines.append(esc(body))
                lines.append("")
            changes = it.get("changes_in_paper", [])
            if changes:
                lines.append("\\noindent\\textbf{Changes in this revision.}")
                lines.append("\\begin{itemize}")
                for ch in changes:
                    lines.append(f"  \\item {esc(ch)}")
                lines.append("\\end{itemize}")
                lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render stage-3 drafts to MD or LaTeX.")
    p.add_argument("--in", dest="in_path", required=True)
    p.add_argument("--out", dest="out_path", required=True)
    p.add_argument("--format", choices=["md", "latex"], default="md")
    p.add_argument("--group-by", choices=["reviewer", "flat"],
                   default="reviewer")
    args = p.parse_args(argv)

    with open(args.in_path, "r", encoding="utf-8") as f:
        items = [json.loads(line) for line in f if line.strip()]

    if not items:
        with open(args.out_path, "w", encoding="utf-8") as f:
            f.write("# No items\n")
        print(f"[render] no items; wrote placeholder to {args.out_path}",
              file=sys.stderr)
        return 0

    group = args.group_by == "reviewer"
    if args.format == "md":
        out = render_md(items, group) if args.format == "md" else render_latex(items, group)

    # Ensure parent directory exists
    parent = os.path.dirname(args.out_path)
    if parent:
        os.makedirs(parent, exist_ok=True)

    with open(args.out_path, "w", encoding="utf-8") as f:
        f.write(out)

    print(f"[render] wrote {len(items)} items as {args.format} "
          f"to {args.out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())